apiVersion: v1
kind: Service
metadata:
  name: go-api
  namespace: retro-filter
  labels:
    app: retro-filter
    component: go-api
spec:
  type: NodePort
  selector:
    app: retro-filter
    component: go-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
