apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: retro-filter
  labels:
    app: retro-filter
    component: redis
spec:
  type: ClusterIP
  selector:
    app: retro-filter
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
